import Head from 'next/head'
import Layout from '../components/Layout'
import Link from 'next/link'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Mon Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta property='og:title' content={`Mon Portfolio`} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='flex flex-col relative bg-slate-900 text-white'>
        <div className='flex justify-center flex-col'>
          <h1 className='mt-[50px] m-auto sm:text-8xl text-6xl text-center'>Mon Portfolio</h1>
          <h2 className='m-auto mt-20 text-2xl'>Accéder au site en tant que :</h2>
        <div className='m-auto flex flex-col lg:flex-row text-center justify-center mt-28 text-2xl w-full'>
          <Link href="/Accueil" className='w-full'>
            <button aria-label='Site Visiteur' className='w-[60%] max-w-[40ch] h-[100px] border border-white border-solid uppercase py-2 duration-300 relative after:absolute after:top-0 after:right-full after:bg-white after:z-10 after:w-full after:h-full overflow-hidden hover:after:translate-x-full after:duration-300 hover:text-black'>
              <h2 className='relative z-20'>
                VISITEUR
              </h2>
            </button>
         </Link>
         <Link href="/Admin/LoginPage" className='w-full'>
            <button aria-label='Site Administrateur' className='lg:ml-[30px] mt-[30px] lg:mt-[0px] w-[60%] max-w-[40ch] h-[100px] border border-white border-solid uppercase py-2 duration-300 relative after:absolute after:top-0 after:right-full after:bg-white after:z-10 after:w-full after:h-full overflow-hidden hover:after:translate-x-full after:duration-300 hover:text-black'>
              <h2 className='relative z-20'>
                ADMINISTRATEUR
              </h2>
            </button>
         </Link>
        </div>
      </div>
      </section>
      <section className='mt-[150px]' aria-roledescription="Contenu expliquant ce qu'est le site">
        <div className='text-3xl flex justify-center flex-col w-[90%] m-auto items-center leading-[42px]'>
          Bienvenue sur mon portfolio, ici je vais vous présenter les travaux que j'ai efféctué durant ces derniers mois, parmis ceux-ci vous pourrez constater 
          plusieurs langages de programation différents, comme par exemple du HTML/CSS ou du javascript, mais aussi des languages un peu plus avancés comme du React et du Next 
          associés suivant les projets à des langages de Backend. <br></br>
          Pour ce faire, les projets seront disposés sous forme de Cards et cliquables pour accéder à une page avec plus de contenu. Ainsi, cela sera un moyen pour vous de vous procurer la description du projet
          sous forme de pdf. <br></br>
          À coté de cela, je vous propose également dans une partie de ce site d'en apprendre plus sur moi, mes compétences et mes projets afin que vous me connaissiez mieux. Sur cette page, je vous laisse également la possibilité de 
          télécharger mon CV au format pdf.
          <br></br>
          <span className='mt-8 mb-24'>Bonne lecture !</span>
        </div>
      </section>
      
      
   
    </Layout>
  )
}
